try:
  print("test")
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")